name: history_state_notifier
description: Extends state_notifier to add a history feature that allows for undo/redo operations.
version: 0.0.2
repository: https://github.com/timcreatedit/history_state_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  state_notifier: ^0.7.1
  meta: ^1.7.0

dev_dependencies: